version: '3.4'

services:
  taskmanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  taskmanagemnetdb:
    container_name: taskmanagemnetdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123456@Aa
    restart: always
    ports:
      - "1433:1433"